### PR TITLE
Pebble slingshot ammo

### PR DESCRIPTION
**Pull request by Guysus**

### CODE REVIEW

**Review by Jeff-Moreau — APPROVED** [review]
Looks Good

**Review by Saretzky — CHANGES_REQUESTED** [review]
add a row to the data table and connect in within the blueprint

**Comment by Jeff-Moreau** [comment]
> add a row to the data table and connect in within the blueprint

I swear there was an edit to that before.. there were 2 files here not 1
maybe i missed it.. but pretty sure there were 2 files in here previously when i approved

**Review by Jeff-Moreau — APPROVED** [review]
Looks Good

**Review by Saretzky — APPROVED** [review]
looks good

**Pull request merged**
