### PR TITLE
Added Tarantula Assets.

### PR DESCRIPTION
**Pull request by AMacLeod99**

### CODE REVIEW

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
I would make sure that all files are named according to what the model is so we do not get confused

**Review by CrazyTobi — CHANGES_REQUESTED** [review]
I agree with Jeff

**Review by CrazyTobi — APPROVED** [review]
Looks good

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Seem to have doubled up on assets here? should you not remove the spider_ assets and just leave the Tarantula ones?

**Review by Jeff-Moreau — APPROVED** [review]
Looks Better

**Pull request merged**
