### PR TITLE
Beach asset

### PR DESCRIPTION
**Pull request by MysticAmazon**
two files where to big to commit with the other stuff, i think i fixed that by ignoring and adding to the .gitignore, that could have been wrong if yes just let me know.

### CODE REVIEW

**Review by Saretzky — CHANGES_REQUESTED** [review]
rename the files to represent what they are

**Review by AMacLeod99 — APPROVED** [review]

**Comment by MysticAmazon** [comment]
> rename the files to represent what they are

Changes made

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Yup rename files to better understand what they are would be nice

**Comment by MysticAmazon** [comment]
> Yup rename files to better understand what they are would be nice

just made the changes :)

**Pull request merged**
