### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Saretzky**
added data table for easy editing, added name to leaf in item data table, cleaned some code up

### CODE REVIEW

**Review by Jeff-Moreau — APPROVED** [review]
Looks Good. The Ammos wording and naming convention is throwing me off. but the code looks good

**Comment by Saretzky** [comment]
> Looks Good. The Ammos wording and naming convention is throwing me off. but the code looks good

Any suggestions to make it better?

**Comment by Jeff-Moreau** [comment]
> > Looks Good. The Ammos wording and naming convention is throwing me off. but the code looks good
> 
> Any suggestions to make it better?

I think that is why I wrote what I did. I may not like it but I get what you are doing for the plural. I just cant think of anything better. At least not right now anyways

**Comment by Saretzky** [comment]
> > > Looks Good. The Ammos wording and naming convention is throwing me off. but the code looks good
> > 
> > 
> > Any suggestions to make it better?
> 
> I think that is why I wrote what I did. I may not like it but I get what you are doing for the plural. I just cant think of anything better. At least not right now anyways

Feel free to change it if you get a good idea for it (and anyone else who is reading this)

**Pull request merged**
