### PR TITLE
Lvl one beat boss scene

### PR DESCRIPTION
**Pull request by CrazyTobi**
Got cutscene set up and working via tests just needs to be set up to play when the crocodile dies which can be set up when the boss is within level

### CODE REVIEW

**Comment by CrazyTobi** [comment]
also added new model for the crocodile and gave him a death animation

**Review by Saretzky — CHANGES_REQUESTED** [review]
you're no adding the video
image

image

**Review by AMacLeod99 — APPROVED** [review]

**Comment by CrazyTobi** [comment]
for the first image all the file sources open up like that but they work but I did move the mp4 file into the right project folder and recreated the file source from it and fixed the message in the second image

**Review by Saretzky — CHANGES_REQUESTED** [review]
increase the resolution, it's pretty low res
image

**Review by Saretzky — CHANGES_REQUESTED** [review]
is there any way to make the video over, with less shadow pop in and better lighting (maybe turn off the shadows entirely for the cutscene). right now the shadows moving and popping in is very distracting

**Review by Saretzky — APPROVED** [review]
looks good

**Pull request merged**
