### PR TITLE
Made adjustments to the 4 levels and the material strengths

### PR DESCRIPTION
**Pull request by Kenster833**
Made tweaks to the strength and power values of the various materials, made a change to the lighting, adjusted all 4 levels skyboxes.
Let me know if its not bright enough on level 1

### CODE REVIEW

**Review by Saretzky — CHANGES_REQUESTED** [review]
i would say make the skybox even brighter. this is what is looks like for me when looking straight ahead
image

this is what it looks like when looking up
image

**Review by AMacLeod99 — APPROVED** [review]

**Review by Saretzky — CHANGES_REQUESTED** [review]
looks a lot better, but I would say even brighter. imo the sky should be brighter than the ground. 

this is what it looks like on my end:
image

**Review by Saretzky — APPROVED** [review]
looks good

**Review by Guysus — COMMENTED** [review]
looks good

**Pull request merged**
