### PR TITLE
Settings menu programming

### PR DESCRIPTION
**Pull request by Kenster833**
Programming for buttons and sliders

### CODE REVIEW

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Screen is messed up and button presses are not functioning

**Review by CrazyTobi — CHANGES_REQUESTED** [review]
Same as what jeff said on my end

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
There are white squares when you hover over the buttons Tammy had this issue yesterday please fix.. also do the buttons actually edit the settings in the game and do they stay when you leave the settings menu?

**Review by CrazyTobi — CHANGES_REQUESTED** [review]
I get the white boxes as well and also wondering if the settings changes stay when you back out. I also noticed with the screen resolution it generates a second screen with the new resolution over the first screen with the old resolution and the new screen doesn't allow me to click anything

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Game Crashes on FPS Change
Settings dont seem to carry over to the game, seems to reset as soon as you leave the settings menu

**Review by Saretzky — CHANGES_REQUESTED** [review]
the game crashed when changing fps cap (so bad that i had to delete and reclone the project)

some things are not anchored properly

https://github.com/Guysus/SteveSloth/assets/129458993/3ad8df66-1506-4aeb-aae7-9bb604e50a98

the icons block clicking

https://github.com/Guysus/SteveSloth/assets/129458993/170299a1-b3e7-40f9-91ac-9cdd1d59e264

use comments to wrap your blueprints

eg:
image

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Icons at top still prevent clicking of the different tabs

**Review by Saretzky — CHANGES_REQUESTED** [review]
no crash, the posts in the background are still not anchored properly
image
image


there should also be a default screen, so when you open it it doesnt start all white
image

**Comment by Kenster833** [comment]
> no crash, the posts in the background are still not anchored properly image image
> 
> there should also be a default screen, so when you open it it doesnt start all white image

The posts are anchored centered and where they were set in the previous design task, the controller image is slightly off the nails in the post because the vibration symbol above is factored into the width of the image adjusting it to be off center slightly if you only factor in the controller itself.

As for the white space that is a design task issue and should have been brought up during the pull request of that task, I feel like this is outside the scope of the current task

**Comment by Jeff-Moreau** [comment]
Ill fix what is wrong.. lets just get it in the game at this point

**Review by Jeff-Moreau — APPROVED** [review]

**Review by CrazyTobi — APPROVED** [review]
No crashing on my end, changing to approve to get into game

**Review by Saretzky — APPROVED** [review]
alright, lets get it in

**Pull request merged**
