### PR TITLE
Swim Control Logic

### PR DESCRIPTION
**Pull request by Kenster833**
Added logic for swimming

### CODE REVIEW

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Looks good.. needs expansion but can be done later
Just need to add the Action Input and then add to the IMC aswell

**Review by Saretzky — CHANGES_REQUESTED** [review]
add input action

**Review by Saretzky — APPROVED** [review]
good baseline, will need tweaking in a future task, but good for now

**Review by Jeff-Moreau — APPROVED** [review]
Cool

**Pull request merged**
