### PR TITLE
World map setup

### PR DESCRIPTION
**Pull request by MysticAmazon**

### CODE REVIEW

**Review by Saretzky — CHANGES_REQUESTED** [review]
in BP_FogOfWar, can you explain what this part is doing 
image

a little semantic, but in the BP_WorldCam the comment should say "divide by two", dividing by half means something different
image

In the BP_Player, you need to put the data table in the slot, otherwise it will crash
image


when I hit M it looks like this
image

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
1. You have to hold the M key to get the map up.
2. The map does not uncover anything it is just black.
3. Player movement controls should be turned off while the map is up

**Comment by MysticAmazon** [comment]
> 1. You have to hold the M key to get the map up.
> so i had set it up that way intentionally, i can change that if prefered
>     2. The map does not uncover anything it is just black.
> as the player  moves the map should be uncovered it is working on my end, let me know if it doesn't for you for some reason
>     3. Player movement controls should be turned off while the map is up
    i can fix this

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Awesome Changes
Just the Fog of war does not seem to be working.
Just a reminder from discussion in class

**Review by Saretzky — CHANGES_REQUESTED** [review]
raise the black a little, it looks like the top of the terrain is clipping through
image

also, it's not updating even when in the open

https://github.com/Guysus/SteveSloth/assets/129458993/0888f7a2-9a4d-4b12-b808-a3405aeeedb6

**Comment by Saretzky** [comment]
video for reference 
https://github.com/Guysus/SteveSloth/assets/129458993/bc039dcc-1ee6-405f-af34-5790af2925a3

**Review by Jeff-Moreau — APPROVED** [review]
Works on My end now. Good job, well done

**Review by Saretzky — CHANGES_REQUESTED** [review]
Raise it a little so this doesnt show through the map: 
Screenshot 2024-05-28 195422

The trees still block the line trace

**Review by Saretzky — CHANGES_REQUESTED** [review]
last thing, can you make the player icon on the map more visible (higher colour contrast or something like that)?

**Comment by MysticAmazon** [comment]
> last thing, can you make the player icon on the map more visible (higher colour contrast or something like that)?

yeah no problem, would you like a bit bigger also or just brighter?

**Comment by Saretzky** [comment]
> > last thing, can you make the player icon on the map more visible (higher colour contrast or something like that)?
> 
> yeah no problem, would you like a bit bigger also or just brighter?

Bigger is good too, the easier it is to see the better

**Review by Saretzky — CHANGES_REQUESTED** [review]
still hard to see, maybe a new icon is needed

**Review by Saretzky — APPROVED** [review]
looks good

**Pull request merged**
