### PR TITLE
Possum idle animation

### PR DESCRIPTION
**Pull request by Guysus**

### CODE REVIEW

**Review by Saretzky — COMMENTED** [review]
what is the reason for the new possum asset?

**Review by CrazyTobi — APPROVED** [review]
Looks good, completely understand the the need for new possum asset

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Should also remove Hud from the pull request. Should just ignore it every time you do a pull request

**Review by Jeff-Moreau — APPROVED** [review]
Looks Good

**Pull request merged**
