### PR TITLE
Cliff Assets Added

### PR DESCRIPTION
**Pull request by MysticAmazon**
added two different cliff styles

### CODE REVIEW

**Review by Saretzky — CHANGES_REQUESTED** [review]
rename these to be a bit more descriptive

**Comment by MysticAmazon** [comment]
> Looks good, just wanted to know if the hub snuck it's way in again

it did indeed, i didnt see it before i committed

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Quick Rename of files please

**Comment by MysticAmazon** [comment]
> rename these to be a bit more descriptive

renamed files

**Review by Saretzky — APPROVED** [review]
looks good

**Review by Jeff-Moreau — APPROVED** [review]
Looks Good

**Pull request merged**
