### PR TITLE
Death music

### PR DESCRIPTION
**Pull request by Saretzky**

### CODE REVIEW

**Review by Jeff-Moreau — APPROVED** [review]
2 Death sounds??? Cool..
Question why in Jingles?
Would it not be better to add it to a Steve folder to keep those sounds together?
Just my thoughts

**Comment by Saretzky** [comment]
> 2 Death sounds??? Cool.. Question why in Jingles? Would it not be better to add it to a Steve folder to keep those sounds together? Just my thoughts

Its different than a sound effect, it's like what plays after the death sound effect, So it fits in music more. I'm also adding victory jingles, so i made a jingles folder

**Comment by Jeff-Moreau** [comment]
> > 2 Death sounds??? Cool.. Question why in Jingles? Would it not be better to add it to a Steve folder to keep those sounds together? Just my thoughts
> 
> Its different than a sound effect, it's like what plays after the death sound effect, So it fits in music more. I'm also adding victory jingles, so i made a jingles folder

Sounds good, thanks for the explanation

**Review by CrazyTobi — APPROVED** [review]
Looks good

**Pull request merged**
