### PR TITLE
Crate shatter vfx

### PR DESCRIPTION
**Pull request by Kenster833**
Created folder, created fracture geometry from static mesh, set geometry collection variables and numbers, played around with adjustable damage values.

### CODE REVIEW

**Review by Saretzky — COMMENTED** [review]
does this work for the ammo crate as well?

**Review by Saretzky — CHANGES_REQUESTED** [review]
wait until ammo crate as well

**Review by Saretzky — APPROVED** [review]
looks good  ty

**Review by MysticAmazon — APPROVED** [review]
looks good, now that ammo crate was added

**Pull request merged**
