### PR TITLE
Main menu button programming

### PR DESCRIPTION
**Pull request by MysticAmazon**

### CODE REVIEW

**Review by Saretzky — CHANGES_REQUESTED** [review]
when i hover over the buttons they turn all white
image

**Review by Jeff-Moreau — APPROVED** [review]
Looks better now.. still has a white box around it looks weird.. but all good

**Comment by MysticAmazon** [comment]
> Looks better now.. still has a white box around it looks weird.. but all good

ill check it out !

**Comment by MysticAmazon** [comment]
> Looks better now.. still has a white box around it looks weird.. but all good

All fixed !

**Review by Saretzky — APPROVED** [review]

**Pull request merged**
