### PR TITLE
Intro cutscene

### PR DESCRIPTION
**Pull request by AMacLeod99**
The one thing that needs fixing is making it cover the whole screen so the player can't click around the video and move, but other than that everything is good to go.

### CODE REVIEW

**Review by CrazyTobi — APPROVED** [review]
I like it, looks good!

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Need to fixes the issues for compilation

**Review by Saretzky — CHANGES_REQUESTED** [review]
fix conflicts

**Review by Saretzky — CHANGES_REQUESTED** [review]
this need some work:
1. it's completely silent
2. it's just static images
(just my opinion, but I think the cutscene needs to be a bit more)

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
I think some sound, possibly some transitions between the images.
I think the Static images is a little less than what is expected for a cutscene.
But at least some sound and transitions and making it fluid

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
Intro does not play when the level starts.
Music is a nice addition

**Review by Saretzky — CHANGES_REQUESTED** [review]
you added the main menu widget so now it works like this:

https://github.com/Guysus/SteveSloth/assets/129458993/8e915111-1289-44d9-8a6f-d902fd3c38c8

please fix

**Comment by AMacLeod99** [comment]
OK NOW it should be all clear.

**Review by Saretzky — CHANGES_REQUESTED** [review]
I would have this play after you click new game in the menu widget, so the cutscene doesnt play every time you enter level 1, make it so you dont have to click to get out of the cutscene when its finished

theres an error:
image

**Review by Jeff-Moreau — CHANGES_REQUESTED** [review]
still does not start on level opening for me
also i like what elad said about it starting after the level is selected so it does not play everytime

**Comment by AMacLeod99** [comment]
I think until we get a save and load working this as far as I can take this.

**Review by Saretzky — CHANGES_REQUESTED** [review]
make it automatically go to level 1 when the cutscene ends

**Review by Saretzky — CHANGES_REQUESTED** [review]
the intro - add to viewport aren't being used
image

organize these better and wrap it (or wrap the different sections) in a comment (like in tammy's blueprints)
image

**Review by Saretzky — CHANGES_REQUESTED** [review]
wrap both the construct and skip parts in separate comments and label them
image

it waits at the end of the cutscene for a while, instead of using duration consider looking into: https://docs.unrealengine.com/4.27/en-US/BlueprintAPI/Media/MediaPlayer/OnEndReached/

**Review by Saretzky — APPROVED** [review]
looks good

**Review by Jeff-Moreau — APPROVED** [review]
Yup yup

**Pull request merged**
